### PR TITLE
add atomic file writer

### PR DESCRIPTION
**Pull request by owenwater**
For issue #66

### CODE REVIEW

**Comment by owenwater** [comment]
close and re-open the pr for re-run the check.

**Comment by owenwater** [comment]
Hi @deanishe 

Sorry for so many little commits. Some test cases failed because I can't find a way to run test with 2.6 on my machine. Also fix another test cases caused by www.kulturliste-duesseldorf.de. That website is using `https` now so the url string is changed.

**Comment by deanishe** [comment]
Thanks! Looks great. BTW, run the unit tests with `tox` to get them to work with 2.6.

**Comment by owenwater** [comment]
Not a problem. Also thanks for fixing the format and comments for me.

**Comment by deanishe** [comment]
Oh, I just looked at the code that was causing problems in 2.6. Yeah, annoying that there are no context managers.

I wish I'd gone with `pytest` from the start :disappointed: 

I refactored the signal handling to only write once. It still passes the tests, but do you know if the way I've done it is somehow wrong?

**Comment by owenwater** [comment]
The unit test should past. Actually it's a better approach than mine since the write function won't be executed more than once. The signal handler catch the signal but didn't quit the job so the program should back to where it's get interrupted and keep going.

However, there is only one tiny problem.  The reason of it is that the execution order of this decorator is could be different.

For 

    class A(object):
        @uninterruptible
        def fun(self):
            pass

    A().fun()

The execution order is `A().fun()` -> `__get__()` -> `__init__()`  -> back to `__get__()`-> `__call__()`

For 

    @uninterruptible
    def fun(self):
            pass

    fun()

The execution order is `fun()` -> `_call__()`

So in the first example, there is actually a new decorator instance every time function get called. But there's only ONE decorator instance in the second example. It means `_caught_signal` will never be reset  because it's only be initialized in `__init__()` now. So for the scenario  `function called` -> `SIGTERM` -> `System didn't quit` -> `function called again`. The `old_signal_handler` will be executed again in the second call even there is no more `SIGTERM`.

This is not a big issue now because there is only one function using this decorator and it's a class method. But it may cause problem if the decorator is used somewhere else in the future.

**Comment by deanishe** [comment]
If I've understood it correctly, I don't really see that as a problem: the script will terminate after `__call__` completes the first time `_caught_signal` is set.

At any rate, I've added `self._caught_signal = None` as the first line in `__call__`, which should fix the issue.

**Comment by owenwater** [comment]
Most of cases, yes. Just not [guarantee](https://docs.python.org/2/library/signal.html#signal.SIG_IGN).

**Pull request merged**
