### PR TITLE
Pretty printing XML when debugging

### PR DESCRIPTION
**Pull request by WoLpH**
Just a little mod which pretty-prints the XML when writing to a TTY. More readable and easier to debug :)

### CODE REVIEW

**Comment by deanishe** [comment]
Thanks, but pretty printing has already been rejected.

It's more readable, but isn't easier to debug because it means the output on the CLI is different to what is sent to Alfred. As a result, line and column numbers in Alfred error reports are useless, and it could potentially hide other errors. This is why the CLI XML isn't already pretty-printed.

It's simple enough to reformat XML in any decent editor or pipe it through `xmllint`.

For any future pull requests, please follow [the instructions in README.md](https://github.com/deanishe/alfred-workflow#bug-reports-pull-requests), in particular:

- 100% test coverage (which is why Travis CI rejected your PR)
- Pull requests against the `develop` branch, not `master`.

In addition, to save effort, it's usually a good idea to ask in an issue first whether the feature you wish to add is desired, or as in this case, has already been considered and rejected.

**Comment by WoLpH** [comment]
The pull request was meant more as an example, I have the code running for
myself and find it useful.

Didn't want to waste time on a proper pull request until I knew you liked
the feature ;)

**Comment by deanishe** [comment]
> Didn't want to waste time on a proper pull request until I knew you liked the feature

Then why did you waste *my* time by not making clear straight away that it's an "example" or posting an "here's an idea" issue instead?

**Comment by WoLpH** [comment]
I could swear I added a line in the pull request that said it was an example, it was honestly meant as such. Didn't mean to waste your time. 

As for issue versus pull request, can you explain your the issue here? A pull request is essentially an issue with code attached to it, is it not? I could have created a gist instead but that's more complicated and I needed the code anyhow so why not add the code as a form of explanation. I generally find it easier to read the intention from code than from docs.

**Comment by deanishe** [comment]
It's not about issues vs pull requests. It's about the difference between "add this code I wrote to the project" and "what do you think of this?" Issues are inherently not in the former category.

**Comment by WoLpH** [comment]
It was simply a proposal. If you like it I can change it into a proper pull
request, alternatively you can simply close it.

**Comment by deanishe** [comment]
As I said, sending different XML to Alfred than what is printed to a shell is a bad idea.

Generating pretty XML (in the suggested fashion) also triples the XML-generation time.

I'm considering prettifying XML by default if DEBUG is set in v2, but in all likelihood (for the above reason), there'll be no pretty XML under any circumstances.

Pretty XML is a lovely thing, but as noted, it's *extremely* easy to do in a shell with `xmllint` (or any decent editor) when needed, and I'm not convinced that tripling the XML generation time in Alfred-Workflow is worth the trade-off.

**Comment by WoLpH** [comment]
Is performance actually an issue? Here's some results from benchmarking the alfred scriptfilter example

The original:
``` %timeit ET.tostring(root).encode('utf-8')
1000 loops, best of 3: 365 us per loop
```

The pretty version:
```%timeit parseString(ET.tostring(root).encode('utf-8')).toprettyxml()
1000 loops, best of 3: 1.8 ms per loop
```

So effectively:
``` %timeit parseString(out).toprettyxml()
1000 loops, best of 3: 1.4 ms per loop```

Indeed a lot slower but still next to nothing. I personally wouldn't care about 1.4ms at least.

The used XML:
```
  <?xml version="1.0"?>
    <items>
        <item uid="desktop" arg="~/Desktop" valid="YES" autocomplete="Desktop" type="file">
            <title>Desktop</title>
            <subtitle>~/Desktop</subtitle>
            <icon type="fileicon">~/Desktop</icon>
        </item>
        <item uid="flickr" valid="no" autocomplete="flickr">
            <title>Flickr</title>
            <icon>flickr.png</icon>
        </item>
        <item uid="image" autocomplete="My holiday photo" type="file"> 
            <title>My holiday photo</title> 
            <subtitle>~/Pictures/My holiday photo.jpg</subtitle> 
            <icon type="filetype">public.jpeg</icon> 
        </item>
        <item uid="home" arg="~/" valid="YES" autocomplete="Home" type="file">
            <title>Home Folder</title>
            <icon type="fileicon">~/</icon>
            <subtitle>Home folder ~/</subtitle>
            <subtitle mod="shift">Subtext when shift is pressed</subtitle>
            <subtitle mod="fn">Subtext when fn is pressed</subtitle>
            <subtitle mod="ctrl">Subtext when ctrl is pressed</subtitle>
            <subtitle mod="alt">Subtext when alt is pressed</subtitle>
            <subtitle mod="cmd">Subtext when cmd is pressed</subtitle>
            <text type="copy">Text when copying</text>
            <text type="largetype">Text for LargeType</text>
        </item>
    </items>```

**Comment by WoLpH** [comment]
That was on a virtualized linux box btw, on my own system it adds just slightly less than 1ms for the same test:

```
%timeit parseString(out).toprettyxml()
1000 loops, best of 3: 985 µs per loop
```

**Comment by deanishe** [comment]
I understand the performance hit is small, but I don't know how many people out there are sending several hundred results to Alfred per run, at which point the performance hit starts to become noticeable to the user.

Bear in mind that Alfred-Workflow is widely used by novice coders and 0.1s is a significant proportion of the time a workflow run should ideally finish in.

As I said in my first response, pretty-printing (via exactly the method you propose) has already been considered and rejected because of the potential performance hit in a workflow on the one hand and the discrepancy between workflow and shell output on the other.

I'm happy to add pretty printing to v2 *as an option*, probably via a flag set with a magic argument.

I just don't think the performance hit is worth it to use by default when it's so easy to use `xmllint` to achieve the same results.

**Pull request closed without merging**
